### ISSUE TITLE
Redmond2K themes set annoying solid colour background in MATE

### ISSUE THREAD

**Issue by rdrms** [matthewmx86/Redmond2K#3]
Seems to be @base_color that is set as the background in MATE and you cannot change it from that with MATE settings, only when using this GTK theme.

I tried commenting out

.../Redmond2K/gtk-3.0/gtk-general.css
```
.background {
  color: @theme_fg_color;
  background-color: @theme_bg_color; }

.background:backdrop {
  color: @theme_unfocused_fg_color;
  background-color: @theme_bg_color; }
```
but no luck.  Is there some other thing I have to change to make it work nice in MATE? The actual theme looks nice, but overriding the wallpaper makes it non-usable.

**Comment by matthewmx86** [comment]
Try adding this line to the gtk-general.css file:

.caja-desktop-window {
   background-color: transparent;
}

If it works I'll push the fix to all the themes in the next release.

**Comment by rdrms** [comment]
No luck unfortunately, still forcing a solid white background on Redmond2K, blue background on Redmond2K Aqua, etc.  Any other ideas?

**Comment by matthewmx86** [comment]
I will install MATE desktop on my computer and see if I can see what's causing the issues. The GTK inspector should let me know which css file and line is setting the desktop background property, I'm sure it'll be something simple.

**Comment by matthewmx86** [comment]
OK I think I found a solution, I first had some issues I had to fix with MATE desktop on my Arch install I couldn't get the appearance settings to open. Try adding this line to the gtk-general.css fille:

.caja-desktop-window * {
background-color: transparent;
}

It fixed it on my end I was able to get the desktop background back.

**Comment by matthewmx86** [comment]
If that works I've also added a few more updates to style the MATE desktop panel. I haven't committed the updates to the main themes but I've included an archive called MATE-testing.tar.gz in the packages directory which includes the testing version that you can try out until I commit the changes.

**Comment by rdrms** [comment]
That tar.gz works, but it's a slightly different theme (Redmond 97 Millenium, not Redmond 2K), but the default Redmond 97 theme also has the same issue so it appears that you've fixed it.  Thank you so much for your time, I know you made the theme primarily for Xfce but it's nice that you took the time to make it work with MATE.  Feel free to close this issue once you've updated the themes.  Thanks again!

**Comment by matthewmx86** [comment]
No problem glad to hear it worked, I will soon be adding support for the Window decorations in MATE. I like the fact that horizontal gradients are supported in the title bars I could never get it to work in Xfce4. For now I've included a basic Redmond2K window decoration with the default color scheme.

**Comment by matthewmx86** [comment]
Fix accepted and committed to repository, closing issue.
